//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeView
        {
            get
            {
                return SteamVR_Actions.default_ChangeView;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleportHeightUp
        {
            get
            {
                return SteamVR_Actions.default_TeleportHeightUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomingLevelUp
        {
            get
            {
                return SteamVR_Actions.default_ZoomingLevelUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleportHeightDown
        {
            get
            {
                return SteamVR_Actions.default_TeleportHeightDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean ZoomingLevelDown
        {
            get
            {
                return SteamVR_Actions.default_ZoomingLevelDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpdateMap
        {
            get
            {
                return SteamVR_Actions.default_UpdateMap;
            }
        }
        
        public virtual SteamVR_Action_Boolean overviewUP
        {
            get
            {
                return SteamVR_Actions.default_overviewUP;
            }
        }
        
        public virtual SteamVR_Action_Boolean overviewDown
        {
            get
            {
                return SteamVR_Actions.default_overviewDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean OverviewLeft
        {
            get
            {
                return SteamVR_Actions.default_OverviewLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean OverviewRight
        {
            get
            {
                return SteamVR_Actions.default_OverviewRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggleAdd
        {
            get
            {
                return SteamVR_Actions.default_TriggleAdd;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggleDelete
        {
            get
            {
                return SteamVR_Actions.default_TriggleDelete;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
